### ISSUE TITLE
Replace default clock

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-clock-applet#1]
Change the default clock to Status Panel standards:

- [x] Matching dimensions with other Nomad applets.
- [ ] Add option to change the clock font size (in its settings).
- [x] Combine with weather plasmoid; positioned below calendar.

**Comment by UriHerrera** [comment]
Mockup:

![](http://i.imgur.com/cKlbr8d.png)

**Comment by azubieta** [comment]
The clock font size, depends on the size available for the text according to the widget size and other elements being shown with the time. Fixing it will cause the widget to be harder to resize/accommodate inside the panel.

like this case
![spectacle t13069](https://user-images.githubusercontent.com/1138094/29600915-4a9c3e44-879e-11e7-98b6-29406617476f.png)

**Comment by azubieta** [comment]
![spectacle p13069](https://user-images.githubusercontent.com/1138094/29600983-a2d15f68-879e-11e7-98b4-7208e65fd24f.png)
![spectacle u13069](https://user-images.githubusercontent.com/1138094/29600942-67f965e8-879e-11e7-8b42-196ccad0d805.png)
![spectacle j13069](https://user-images.githubusercontent.com/1138094/29600989-abf4c116-879e-11e7-9f27-7cf7a5478be9.png)

**Comment by star-buck** [comment]
looks really nice

**Comment by azubieta** [comment]
@UriHerrera the font issue was fixed in the look and feel can we close this ?

**Comment by UriHerrera** [comment]
Yes.
