### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [nx-desktop/nx-clock-applet#5]
Hello I am a graphic designer and I make contributions to open source projects through the Utopian-io platform, (with them I earn the rewards if you use my proposal) I attach a proposal for your project of an icon and a logo if you like I can send you all the files for you to attach to your project. :-)

![presentacion para github](https://user-images.githubusercontent.com/35604837/39102548-267410fc-4673-11e8-9bfe-4eae7f928d25.png)

**Comment by UriHerrera** [comment]
Hey there! the effort is very much appreciated, however, this project doesn't require a logo or an icon. On the other hand, we do have other projects where you can contribute with your talents like [our icon theme](https://github.com/nomad-desktop/luv-icon-theme).
